### ISSUE TITLE
Change the running command

### ISSUE THREAD

**Issue by hmkoyan-korio** [marara-h/lessons_2023#1]
https://github.com/marara-h/lessons_2023/blob/3abbb84ce42a04a5213e9c6285254372834c2dcf/Docker/Dockerfile#L6

As you have already changed the mode of file to execution mode, chmod +x, in the latest step you can run just writing ./script.sh, or just don't change the mode of file, and run as you did, like: bash script.sh. 
Just for best practice.

**Comment by marara-h** [comment]
Thank you very much for your feedback.
